- Developer:
    - GitHub Repo:
        - href: https://github.com/kyledupont/Homelab
          icon: github.png
    - Portfolio:
        - href: https://kyledupont.github.io/
    - System Map:
        - href: https://kyledupont.github.io/Homelab/
